### ISSUE TITLE
use Yansongda\Supports\Log as BaseLog;

### ISSUE THREAD

**Issue by jxlwqq** [yansongda/supports#9]
Yansongda\Supports\Log class not found

https://github.com/yansongda/pay/blob/ac42d4c128bdb12a147d3fa96413fa81a8cae6fd/src/Log.php#L5

**Comment by yansongda** [comment]
fixed

感谢支持

**Comment by jxlwqq** [comment]
https://packagist.org/packages/yansongda/supports

2.2.* 的版本没有删除
